[2019-01-24 11:48:49,275] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO -  * Restarting with stat
[2019-01-24 11:48:49,518] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} WARNING -  * Debugger is active!
[2019-01-24 11:48:49,519] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO -  * Debugger PIN: 844-574-987
[2019-01-24 11:48:57,298] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO - 127.0.0.1 - - [24/Jan/2019 11:48:57] "POST /video/computer_lab HTTP/1.1" 200 -
[2019-01-24 11:49:00,499] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO - 127.0.0.1 - - [24/Jan/2019 11:49:00] "GET /video_feed HTTP/1.1" 200 -
[2019-01-24 11:49:54,364] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
[2019-01-24 11:49:54,364] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO -  * Restarting with stat
[2019-01-24 11:49:54,601] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} WARNING -  * Debugger is active!
[2019-01-24 11:49:54,601] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO -  * Debugger PIN: 844-574-987
[2019-01-24 11:49:59,007] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO - 127.0.0.1 - - [24/Jan/2019 11:49:59] "GET / HTTP/1.1" 200 -
[2019-01-24 11:49:59,104] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO - 127.0.0.1 - - [24/Jan/2019 11:49:59] "GET /favicon.ico HTTP/1.1" 404 -
[2019-01-24 11:49:59,194] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} ERROR - Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 261, in execute
    write(data)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 227, in write
    self.send_header(key, value)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 412, in send_header
    self.wfile.write("%s: %s\r\n" % (keyword, value))
IOError: [Errno 32] Broken pipe
[2019-01-24 11:50:00,597] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO - 127.0.0.1 - - [24/Jan/2019 11:50:00] "POST /status HTTP/1.1" 200 -
[2019-01-24 11:50:04,188] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO - 127.0.0.1 - - [24/Jan/2019 11:50:04] "POST /video/computer_lab HTTP/1.1" 200 -
[2019-01-24 11:50:15,281] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO - 127.0.0.1 - - [24/Jan/2019 11:50:15] "GET /video_feed HTTP/1.1" 200 -
[2019-01-24 11:50:42,737] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO - 127.0.0.1 - - [24/Jan/2019 11:50:42] "GET /list_experiments HTTP/1.1" 200 -
[2019-01-24 11:50:43,260] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} ERROR - Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 261, in execute
    write(data)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 242, in write
    self.wfile.write(data)
IOError: [Errno 32] Broken pipe
[2019-01-24 11:54:48,109] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO - 127.0.0.1 - - [24/Jan/2019 11:54:48] "POST /video/computer_lab HTTP/1.1" 200 -
[2019-01-24 11:54:59,379] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO - 127.0.0.1 - - [24/Jan/2019 11:54:59] "GET /video_feed HTTP/1.1" 200 -
[2019-01-24 12:43:19,670] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
[2019-01-24 12:43:19,690] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO -  * Restarting with stat
[2019-01-24 12:43:19,935] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} WARNING -  * Debugger is active!
[2019-01-24 12:43:19,935] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO -  * Debugger PIN: 844-574-987
[2019-01-24 12:43:47,746] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO - 127.0.0.1 - - [24/Jan/2019 12:43:47] "GET /test_camera/usb-046d_Logitech_Webcam_C930e_8843357E-video-index0 HTTP/1.1" 200 -
[2019-01-24 12:55:18,957] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
[2019-01-24 12:55:18,957] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO -  * Restarting with stat
[2019-01-24 12:55:19,203] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} WARNING -  * Debugger is active!
[2019-01-24 12:55:19,203] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO -  * Debugger PIN: 844-574-987
[2019-01-24 12:55:20,465] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO - 127.0.0.1 - - [24/Jan/2019 12:55:20] "GET /test_camera/asdad HTTP/1.1" 200 -
[2019-01-24 13:01:16,839] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
[2019-01-24 13:01:16,840] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO -  * Restarting with stat
[2019-01-24 13:01:17,078] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} WARNING -  * Debugger is active!
[2019-01-24 13:01:17,079] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO -  * Debugger PIN: 844-574-987
[2019-01-24 13:01:28,287] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO - 127.0.0.1 - - [24/Jan/2019 13:01:28] "GET / HTTP/1.1" 200 -
[2019-01-24 13:01:30,378] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO - 127.0.0.1 - - [24/Jan/2019 13:01:30] "POST /status HTTP/1.1" 200 -
[2019-01-24 13:01:36,841] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
[2019-01-24 13:01:36,842] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO -  * Restarting with stat
[2019-01-24 13:01:37,078] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} WARNING -  * Debugger is active!
[2019-01-24 13:01:37,078] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO -  * Debugger PIN: 844-574-987
[2019-01-24 13:01:43,903] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO - 127.0.0.1 - - [24/Jan/2019 13:01:43] "GET /login HTTP/1.1" 500 -
[2019-01-24 13:01:44,034] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO - 127.0.0.1 - - [24/Jan/2019 13:01:44] "GET /login?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
[2019-01-24 13:01:44,035] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO - 127.0.0.1 - - [24/Jan/2019 13:01:44] "GET /login?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
[2019-01-24 13:01:44,035] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO - 127.0.0.1 - - [24/Jan/2019 13:01:44] "GET /login?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
[2019-01-24 13:01:44,084] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO - 127.0.0.1 - - [24/Jan/2019 13:01:44] "GET /login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
[2019-01-24 13:01:44,087] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO - 127.0.0.1 - - [24/Jan/2019 13:01:44] "GET /login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
[2019-01-24 13:02:35,578] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO -  * Detected change in '/home/immersivemidiaopenposeclone/build_daq/main.py', reloading
[2019-01-24 13:02:35,623] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO -  * Restarting with stat
[2019-01-24 13:02:35,872] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} WARNING -  * Debugger is active!
[2019-01-24 13:02:35,873] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO -  * Debugger PIN: 844-574-987
[2019-01-24 13:02:39,211] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO -  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
[2019-01-24 13:02:39,211] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO -  * Restarting with stat
[2019-01-24 13:02:39,475] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} WARNING -  * Debugger is active!
[2019-01-24 13:02:39,475] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO -  * Debugger PIN: 844-574-987
[2019-01-24 13:02:42,384] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO - 127.0.0.1 - - [24/Jan/2019 13:02:42] "GET /login HTTP/1.1" 200 -
[2019-01-24 13:02:48,103] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO - 127.0.0.1 - - [24/Jan/2019 13:02:48] "POST /login HTTP/1.1" 500 -
[2019-01-24 13:02:48,222] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO - 127.0.0.1 - - [24/Jan/2019 13:02:48] "GET /login?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
[2019-01-24 13:02:48,224] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO - 127.0.0.1 - - [24/Jan/2019 13:02:48] "GET /login?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
[2019-01-24 13:02:48,226] {/usr/local/lib/python2.7/dist-packages/werkzeug/_internal.py:88} INFO - 127.0.0.1 - - [24/Jan/2019 13:02:48] "GET /login?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
